version: '3'

services:

  php_apache:
    build: ./php_apache                  #значит в дире php_apache лежит Dockerfile
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ./root_directory:/var/www/html
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html

  mysqlserver:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./databases:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 81:8080
